[2025-02-21T09:32:14.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T09:32:13.921453+00:00 [queued]>
[2025-02-21T09:32:14.483+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T09:32:13.921453+00:00 [queued]>
[2025-02-21T09:32:14.483+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T09:32:14.503+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 09:32:13.921453+00:00
[2025-02-21T09:32:14.512+0000] {standard_task_runner.py:57} INFO - Started process 1533 to run task
[2025-02-21T09:32:14.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_postgres_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T09:32:13.921453+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/sync_postgres_dag.py', '--cfg-path', '/tmp/tmppwbl7i1t']
[2025-02-21T09:32:14.517+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask process_kafka_transaction_messages
[2025-02-21T09:32:14.589+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T09:32:13.921453+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T09:32:14.708+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_postgres_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T09:32:13.921453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T09:32:13.921453+00:00'
[2025-02-21T09:32:14.710+0000] {sync_postgres_dag.py:28} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T09:32:14.714+0000] {sync_postgres_dag.py:40} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T09:32:14.719+0000] {sync_postgres_dag.py:45} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T09:32:14.721+0000] {sync_postgres_dag.py:60} INFO - Transaction table created/verified
[2025-02-21T09:32:34.779+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T09:32:34.784+0000] {process_utils.py:131} INFO - Sending 15 to group 1533. PIDs of all processes in the group: [1533]
[2025-02-21T09:32:34.785+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1533
[2025-02-21T09:32:35.726+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T09:32:35.726+0000] {sync_postgres_dag.py:121} ERROR - Fatal error in transaction consumer: Task received SIGTERM signal
[2025-02-21T09:32:35.726+0000] {sync_postgres_dag.py:125} INFO - Closing connections for transaction consumer...
[2025-02-21T09:32:35.803+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1533, status='terminated', exitcode=0, started='09:32:13') (1533) terminated with exit code 0
