[2025-02-21T07:43:34.748+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:43:33.522993+00:00 [queued]>
[2025-02-21T07:43:34.763+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:43:33.522993+00:00 [queued]>
[2025-02-21T07:43:34.764+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T07:43:34.789+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 07:43:33.522993+00:00
[2025-02-21T07:43:34.799+0000] {standard_task_runner.py:57} INFO - Started process 435 to run task
[2025-02-21T07:43:34.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_mysql_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T07:43:33.522993+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/sync_mysql_dag.py', '--cfg-path', '/tmp/tmpivk51dk8']
[2025-02-21T07:43:34.807+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask process_kafka_transaction_messages
[2025-02-21T07:43:34.887+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:43:33.522993+00:00 [running]> on host e5982255e08e
[2025-02-21T07:43:35.002+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_mysql_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T07:43:33.522993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T07:43:33.522993+00:00'
[2025-02-21T07:43:35.003+0000] {sync_mysql_dag.py:27} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T07:43:35.005+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2025-02-21T07:43:35.005+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2025-02-21T07:43:35.006+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Connection complete.
[2025-02-21T07:43:35.112+0000] {conn.py:1268} INFO - Broker version identified as 2.6.0
[2025-02-21T07:43:35.112+0000] {conn.py:1269} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-02-21T07:43:35.113+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('from_mysql_transaction',)
[2025-02-21T07:43:35.114+0000] {sync_mysql_dag.py:38} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T07:43:35.119+0000] {sync_mysql_dag.py:43} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T07:43:35.121+0000] {sync_mysql_dag.py:58} INFO - Transaction table created/verified
[2025-02-21T07:43:35.124+0000] {cluster.py:371} INFO - Group coordinator for transaction_consumer_group is ('coordinator-1', '172.25.0.5', 9092, None)
[2025-02-21T07:43:35.124+0000] {base.py:693} INFO - Discovered coordinator coordinator-1 for group transaction_consumer_group
[2025-02-21T07:43:35.124+0000] {base.py:741} INFO - Starting new heartbeat thread
[2025-02-21T07:43:35.125+0000] {consumer.py:348} INFO - Revoking previously assigned partitions () for group transaction_consumer_group
[2025-02-21T07:43:35.126+0000] {conn.py:380} INFO - <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:45:51.348+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:45:51.349+0000] {conn.py:919} ERROR - <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:45:51.350+0000] {client_async.py:331} WARNING - Node coordinator-1 connection failed -- refreshing metadata
[2025-02-21T07:45:51.451+0000] {base.py:715} WARNING - Marking the coordinator dead (node coordinator-1) for group transaction_consumer_group: Node Disconnected.
[2025-02-21T07:45:51.452+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:48:06.573+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:48:06.574+0000] {conn.py:919} ERROR - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:48:06.574+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-02-21T07:48:06.675+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:50:21.698+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:50:21.699+0000] {conn.py:919} ERROR - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:50:21.699+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-02-21T07:50:21.800+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:52:35.226+0000] {client_async.py:952} INFO - Closing idle connection bootstrap-0, last active 540099 ms ago
[2025-02-21T07:52:35.227+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connected> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. 
[2025-02-21T07:52:36.836+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:52:36.837+0000] {conn.py:919} ERROR - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:52:36.837+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-02-21T07:52:36.938+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:54:52.059+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:54:52.060+0000] {conn.py:919} ERROR - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:54:52.060+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-02-21T07:54:52.161+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
