[2025-02-21T08:10:24.830+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:10:23.256656+00:00 [queued]>
[2025-02-21T08:10:24.843+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:10:23.256656+00:00 [queued]>
[2025-02-21T08:10:24.843+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T08:10:24.862+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_amount_messages> on 2025-02-21 08:10:23.256656+00:00
[2025-02-21T08:10:24.873+0000] {standard_task_runner.py:57} INFO - Started process 229 to run task
[2025-02-21T08:10:24.878+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_mysql_to_postgres_transaction_and_amount', 'process_kafka_amount_messages', 'manual__2025-02-21T08:10:23.256656+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/sync_mysql_dag.py', '--cfg-path', '/tmp/tmpxvdzyzb3']
[2025-02-21T08:10:24.880+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask process_kafka_amount_messages
[2025-02-21T08:10:24.947+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:10:23.256656+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T08:10:25.061+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_mysql_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_amount_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T08:10:23.256656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T08:10:23.256656+00:00'
[2025-02-21T08:10:25.062+0000] {sync_mysql_dag.py:129} INFO - Starting Kafka consumer for amount messages...
[2025-02-21T08:10:25.067+0000] {sync_mysql_dag.py:141} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T08:10:25.074+0000] {sync_mysql_dag.py:146} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T08:10:25.076+0000] {sync_mysql_dag.py:160} INFO - Amount table created/verified
[2025-02-21T08:15:03.323+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T08:15:03.324+0000] {process_utils.py:131} INFO - Sending 15 to group 229. PIDs of all processes in the group: [229]
[2025-02-21T08:15:03.325+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 229
[2025-02-21T08:15:04.130+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T08:15:04.131+0000] {sync_mysql_dag.py:213} ERROR - Fatal error in amount consumer: Task received SIGTERM signal
[2025-02-21T08:15:04.131+0000] {sync_mysql_dag.py:217} INFO - Closing connections for amount consumer...
[2025-02-21T08:15:04.182+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=229, status='terminated', exitcode=0, started='08:10:24') (229) terminated with exit code 0
