[2025-02-21T08:08:13.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:08:12.371451+00:00 [queued]>
[2025-02-21T08:08:13.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:08:12.371451+00:00 [queued]>
[2025-02-21T08:08:13.710+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T08:08:13.725+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 08:08:12.371451+00:00
[2025-02-21T08:08:13.733+0000] {standard_task_runner.py:57} INFO - Started process 183 to run task
[2025-02-21T08:08:13.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_mysql_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T08:08:12.371451+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/sync_mysql_dag.py', '--cfg-path', '/tmp/tmpdy9m2rav']
[2025-02-21T08:08:13.738+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask process_kafka_transaction_messages
[2025-02-21T08:08:13.803+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:08:12.371451+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T08:08:13.911+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_mysql_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T08:08:12.371451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T08:08:12.371451+00:00'
[2025-02-21T08:08:13.913+0000] {sync_mysql_dag.py:27} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T08:08:13.918+0000] {sync_mysql_dag.py:39} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T08:08:13.926+0000] {sync_mysql_dag.py:44} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T08:08:13.927+0000] {sync_mysql_dag.py:59} INFO - Transaction table created/verified
[2025-02-21T08:08:59.265+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T08:08:59.267+0000] {process_utils.py:131} INFO - Sending 15 to group 183. PIDs of all processes in the group: [183]
[2025-02-21T08:08:59.267+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 183
[2025-02-21T08:08:59.936+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T08:08:59.937+0000] {sync_mysql_dag.py:119} ERROR - Fatal error in transaction consumer: Task received SIGTERM signal
[2025-02-21T08:08:59.937+0000] {sync_mysql_dag.py:123} INFO - Closing connections for transaction consumer...
[2025-02-21T08:09:00.003+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=183, status='terminated', exitcode=0, started='08:08:12') (183) terminated with exit code 0
