[2025-02-21T08:15:26.926+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:15:25.620662+00:00 [queued]>
[2025-02-21T08:15:26.941+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:15:25.620662+00:00 [queued]>
[2025-02-21T08:15:26.941+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T08:15:26.964+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_amount_messages> on 2025-02-21 08:15:25.620662+00:00
[2025-02-21T08:15:26.976+0000] {standard_task_runner.py:57} INFO - Started process 313 to run task
[2025-02-21T08:15:26.986+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_mysql_to_postgres_transaction_and_amount', 'process_kafka_amount_messages', 'manual__2025-02-21T08:15:25.620662+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/sync_mysql_dag.py', '--cfg-path', '/tmp/tmp4k8e1osw']
[2025-02-21T08:15:26.989+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask process_kafka_amount_messages
[2025-02-21T08:15:27.114+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T08:15:25.620662+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T08:15:27.248+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_mysql_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_amount_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T08:15:25.620662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T08:15:25.620662+00:00'
[2025-02-21T08:15:27.251+0000] {sync_mysql_dag.py:130} INFO - Starting Kafka consumer for amount messages...
[2025-02-21T08:15:27.258+0000] {sync_mysql_dag.py:142} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T08:15:27.267+0000] {sync_mysql_dag.py:147} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T08:15:27.269+0000] {sync_mysql_dag.py:161} INFO - Amount table created/verified
[2025-02-21T08:23:33.003+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T08:23:33.006+0000] {process_utils.py:131} INFO - Sending 15 to group 313. PIDs of all processes in the group: [313]
[2025-02-21T08:23:33.006+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 313
[2025-02-21T08:23:33.365+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T08:23:33.366+0000] {sync_mysql_dag.py:214} ERROR - Fatal error in amount consumer: Task received SIGTERM signal
[2025-02-21T08:23:33.367+0000] {sync_mysql_dag.py:218} INFO - Closing connections for amount consumer...
[2025-02-21T08:23:33.421+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=313, status='terminated', exitcode=0, started='08:15:26') (313) terminated with exit code 0
