[2025-02-21T09:16:43.248+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:16:42.019684+00:00 [queued]>
[2025-02-21T09:16:43.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:16:42.019684+00:00 [queued]>
[2025-02-21T09:16:43.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T09:16:43.283+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_amount_messages> on 2025-02-21 09:16:42.019684+00:00
[2025-02-21T09:16:43.292+0000] {standard_task_runner.py:57} INFO - Started process 1288 to run task
[2025-02-21T09:16:43.297+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_postgres_to_postgres_transaction_and_amount', 'process_kafka_amount_messages', 'manual__2025-02-21T09:16:42.019684+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/sync_postgres_dag.py', '--cfg-path', '/tmp/tmp866s6aa9']
[2025-02-21T09:16:43.299+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask process_kafka_amount_messages
[2025-02-21T09:16:43.364+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:16:42.019684+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T09:16:43.462+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_postgres_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_amount_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T09:16:42.019684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T09:16:42.019684+00:00'
[2025-02-21T09:16:43.463+0000] {sync_postgres_dag.py:129} INFO - Starting Kafka consumer for amount messages...
[2025-02-21T09:16:43.467+0000] {sync_postgres_dag.py:141} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T09:16:43.473+0000] {sync_postgres_dag.py:146} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T09:16:43.475+0000] {sync_postgres_dag.py:160} INFO - Amount table created/verified
[2025-02-21T09:16:43.587+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.588+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.588+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.588+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.588+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.589+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.589+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.589+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.589+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.589+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.590+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.591+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.592+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.593+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.594+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.595+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.596+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.597+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.598+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.599+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.600+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.601+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.601+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.601+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.601+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.601+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.602+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.602+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.602+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.602+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.602+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.603+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.604+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.604+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.604+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.604+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:16:43.604+0000] {sync_postgres_dag.py:209} ERROR - Error processing amount message: year 57111 is out of range
[2025-02-21T09:30:23.345+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T09:30:23.348+0000] {process_utils.py:131} INFO - Sending 15 to group 1288. PIDs of all processes in the group: [1288]
[2025-02-21T09:30:23.348+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1288
[2025-02-21T09:30:23.770+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T09:30:23.770+0000] {sync_postgres_dag.py:213} ERROR - Fatal error in amount consumer: Task received SIGTERM signal
[2025-02-21T09:30:23.771+0000] {sync_postgres_dag.py:217} INFO - Closing connections for amount consumer...
[2025-02-21T09:30:23.843+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1288, status='terminated', exitcode=0, started='09:16:42') (1288) terminated with exit code 0
